version: '3.4'

services:
  eventstore.db:
    image: eventstore/eventstore:21.10.8-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_IP=192.168.33.10
      - EVENTSTORE_EXT_IP=192.168.33.10
      - EVENTSTORE_CERTIFICATE_FILE=/eventstore.p12
      - EVENTSTORE_CERTIFICATE_PASSWORD=eventstore
      - EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/etc/ssl/certs
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore-data:/var/lib/eventstore
      - ./certs/eventstore.p12:/eventstore.p12:ro
      - ./certs/eventstore-local.crt:/etc/ssl/certs/eventstore.crt:ro
    networks:
      app_net:
        ipv4_address: 192.168.33.10

  nodejs:
    image: node:14
    working_dir: /var/code
    volumes:
      - .:/var/code
      - /var/code/node_modules
    command: bash -c "tail -f /dev/null"
    networks:
      - app_net

volumes:
  eventstore-data:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.33.0/24"
