version: '3.4'

services:
  eventstore.db:
    image: eventstore/eventstore:21.10.8-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_CLUSTER_DNS=cluster.tests.node-eventstore-client.local
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=node1.tests.node-eventstore-client.local
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
#      - EVENTSTORE_DISCOVER_VIA_DNS=false
#      - EVENTSTORE_GOSSIP_SEED=192.168.33.10:2113,192.168.33.11:2113,192.168.33.12:2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_IP=192.168.33.10
      - EVENTSTORE_EXT_IP=192.168.33.10
      - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node1/node1.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node1/node1.key
      - EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/etc/eventstore/certs/ca
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2113:2113"
    networks:
      app_net:
        aliases:
          - cluster.tests.node-eventstore-client.local
          - node1.tests.node-eventstore-client.local
        ipv4_address: 192.168.33.10
    volumes:
      - eventstore1-data:/var/lib/eventstore
      - ./certs:/etc/eventstore/certs:ro

  eventstore.db2:
    image: eventstore/eventstore:21.10.8-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_CLUSTER_DNS=cluster.tests.node-eventstore-client.local
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=node2.tests.node-eventstore-client.local
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
#      - EVENTSTORE_DISCOVER_VIA_DNS=false
#      - EVENTSTORE_GOSSIP_SEED=192.168.33.10:2113,192.168.33.11:2113,192.168.33.12:2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_IP=192.168.33.11
      - EVENTSTORE_EXT_IP=192.168.33.11
      - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node2/node2.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node2/node2.key
      - EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/etc/eventstore/certs/ca
    expose:
      - "1113"
      - "1112"
      - "2113"
    networks:
      app_net:
        aliases:
          - cluster.tests.node-eventstore-client.local
          - node2.tests.node-eventstore-client.local
        ipv4_address: 192.168.33.11
    volumes:
      - eventstore2-data:/var/lib/eventstore
      - ./certs:/etc/eventstore/certs:ro

  eventstore.db3:
    image: eventstore/eventstore:21.10.8-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_CLUSTER_DNS=cluster.tests.node-eventstore-client.local
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=node3.tests.node-eventstore-client.local
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
#      - EVENTSTORE_DISCOVER_VIA_DNS=false
#      - EVENTSTORE_GOSSIP_SEED=192.168.33.10:2113,192.168.33.11:2113,192.168.33.12:2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_IP=192.168.33.12
      - EVENTSTORE_EXT_IP=192.168.33.12
      - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node3/node3.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node3/node3.key
      - EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/etc/eventstore/certs/ca
    expose:
      - "1113"
      - "1112"
      - "2113"
    networks:
      app_net:
        aliases:
          - cluster.tests.node-eventstore-client.local
          - node3.tests.node-eventstore-client.local
        ipv4_address: 192.168.33.12
    volumes:
      - eventstore3-data:/var/lib/eventstore-data
      - ./certs:/etc/eventstore/certs:ro

  nodejs:
    image: node:12
    working_dir: /var/code
    volumes:
      - .:/var/code
      - /var/code/node_modules
    command: bash -c "tail -f /dev/null"
    networks:
      - app_net

volumes:
  eventstore1-data:
  eventstore2-data:
  eventstore3-data:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.33.0/24"
